services:
# Start up old versions of mariadb, nginx and redis for demonstration purposes
  mariadb:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    labels:
      - "diun.enable=true"
      # - "diun.watch_repo=true"
      # - "diun.sort_tags=semver"
      # - "diun.max_tags=1" 

  nginx:
    image: nginx:1.28
    ports:
      - "8080:80"
    labels:
      - "diun.enable=true"
      # - "diun.watch_repo=true"
      # - "diun.sort_tags=semver"
      # - "diun.max_tags=1"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    labels:
      - "diun.enable=true"
      # - "diun.watch_repo=true"        
      # - "diun.sort_tags=semver"       
      # - "diun.max_tags=1"          
